repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: fmt
        name: fmt
        language: rust
        types: [rust]
        entry: cargo fmt --
#    -   id: clippy
#        name: clippy
#        language: rust
#        types: [rust]
#        pass_filenames: false
#        entry: cargo clippy --workspace -- -D warnings
