[package]
name = "x32_screen_saver"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "env"] }
anyhow = "1.0.82"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
x32_lib = { path = "../x32_lib" }
osc_lib = { path = "../osc_lib" }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1.0"
tempfile = "3.10.1"
