[package]
name = "x32_core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
osc_lib = { path = "../osc_lib" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
