[package]
name = "x32_reaper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
x32_lib = { path = "../x32_lib" }
anyhow = "1.0.82"
config = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
