[package]
name = "x32_reaper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
anyhow = "1.0.82"

osc_lib = { path = "../osc_lib" }
x32_lib = { path = "../x32_lib" }
