[package]
name = "x32_get_scene"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
osc_lib = { path = "../osc_lib" }
x32_lib = { path = "../x32_lib" }
