[package]
name = "x32_punch_control"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
anyhow = "1.0.86"
portmidi = "0.2.0"

osc_lib = { path = "../osc_lib" }
x32_lib = { path = "../x32_lib" }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
