[package]
name = "x32_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
osc_lib = { path = "../osc_lib" }

[features]
dca = []
channel = []
auxin = []
bus = []
mtx = []
main_bus = []
fx = []
fxrtn = []
output = []
headamp = []
show = []
misc = []
prefstat = []
libs = []
