[package]
name = "x32_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
osc_lib = { path = "../osc_lib" }
bitflags = "2.5.0"
lazy_static = "1.4.0"

[features]
default = []
dca = []
fx = []
bus = []
auxin = []
channel = []
common = []
error = []
fxrtn = []
headamp = []
libs = []
main_bus = []
misc = []
mtx = []
output = []
prefstat = []
show = []
cfg_main = []
