[package]
name = "x32_copy_fx"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
lazy_static = "1.4.0"
x32_lib = { path = "../x32_lib" }
osc_lib = { path = "../osc_lib" }
