[package]
name = "x32_tap"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
osc_lib = { path = "../osc_lib" }
anyhow = "1.0.82"
crossterm = "0.27.0"
