[package]
name = "x32_replay"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
anyhow = "1.0.82"
x32_lib = { path = "../x32_lib" }
osc_lib = { path = "../osc_lib" }
chrono = { version = "0.4.38", features = ["serde"] }
crossbeam-channel = "0.5.12"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
tempfile = "3.10.1"

[[bin]]
name = "mock_server"
path = "tests/mock_server.rs"
