name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build on ${{ matrix.os }} for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Desktop Platforms
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            test: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            test: true
          - os: macos-latest
            target: x86_64-apple-darwin
            test: true
          - os: macos-latest
            target: aarch64-apple-darwin
            test: true

          # Mobile Platforms (build only)
         # - os: ubuntu-latest
         #   target: aarch64-linux-android
         #   test: false
         # - os: macos-latest
         #   target: aarch64-apple-ios
         #   test: false
          # - os: macos-latest
          #   target: aarch64-apple-ios-sim
          #   test: false

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        rust-version: stable
        target: ${{ matrix.target }}

    - name: Build
      run: cargo build --workspace --release --target ${{ matrix.target }}

    - name: Run tests
      if: matrix.test == true
      run: cargo test --workspace --release --target ${{ matrix.target }}
