name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build on ${{ matrix.os }} for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Desktop Platforms
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            test: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            test: true
          - os: macos-latest
            target: x86_64-apple-darwin
            test: true
          - os: macos-latest
            target: aarch64-apple-darwin
            test: true

          # Mobile Platforms (build only)
          - os: ubuntu-latest
            target: aarch64-linux-android
            test: false
          - os: macos-latest
            target: aarch64-apple-ios
            test: false
          # - os: macos-latest
          #   target: aarch64-apple-ios-sim
          #   test: false

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --workspace --release --target ${{ matrix.target }}

    - name: Run tests
      if: matrix.test == true
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace --release --target ${{ matrix.target }}
